services:
    _defaults:
        autowire: true
        autoconfigure: true

    Plugins\TrustpilotReview\Widget\TrustpilotWidget:
        tags: ['widget']

    Plugins\TrustpilotReview\Service\TrustpilotService:
        public: true

    Plugins\TrustpilotReview\Bootstrap:
        public: true
